/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 brake1.gltf 
Author: Vladi (https://sketchfab.com/vladivpg)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/brake-disk-and-caliper-5feda9dbf20a49cf9fd29d550e55e4b9
Title: Brake Disk and Caliper
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/public/brake1/brake1.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.016}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.CalliperBrakeFluidLineBolts_Geo_BrakeDisk_Mat2_0.geometry} material={materials.BrakeDisk_Mat2} rotation={[Math.PI / 2, 0, 0]} />
            <mesh geometry={nodes.BrakeCalliper_Geo_BrakeDisk_Mat_0.geometry} material={materials.BrakeDisk_Mat} rotation={[Math.PI / 2, 0, 0]} />
          </group>
          <mesh geometry={nodes.polySurface5_BrakeDisk_Mat_0.geometry} material={materials.BrakeDisk_Mat} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.polySurface6_BrakeDisk_Mat1_0.geometry} material={materials.BrakeDisk_Mat1} rotation={[-Math.PI / 2, 0, 0]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/brake1.gltf')
