/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Chasis1.gltf 
Author: Gerhald (https://sketchfab.com/Gerhald)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/car-chassis-461d16d1a5ac44f58323ac4b7493b043
Title: Car Chassis
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/public/Chasis1/Chasis1.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.1}>
        <group position={[41.976, 3.137, 0]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Cassis_chassis_0.geometry} material={materials.chassis} />
          <mesh geometry={nodes.Cassis_chassis_0_1.geometry} material={materials.chassis} />
          <mesh geometry={nodes.Cassis_chassis_0_2.geometry} material={materials.chassis} />
        </group>
        <group position={[193.411, 47.662, 0]} rotation={[-Math.PI, 0, 0]}>
          <group position={[132.839, 47.662, 238.857]}>
            <mesh geometry={nodes.Weel_2_Weel_2_0.geometry} material={materials.Weel_2} />
            <mesh geometry={nodes.Weel_2_Weel_2_0_1.geometry} material={materials.Weel_2} />
          </group>
        </group>
        <group position={[-131.737, 47.662, 0]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object133_Weel_0.geometry} material={materials.Weel} position={[0, -81.248, 0]} />
        </group>
        <mesh geometry={nodes.Object134_Weel_0.geometry} material={materials.Weel} position={[-131.737, 47.662, 0]} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/Chasis1.gltf')
