/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Exhaust1.gltf 
Author: Silver10211 (https://sketchfab.com/Silver10211)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/valvetronic-quad-exhaust-system-bb6be6106fce465698548917732c4b13
Title: Valvetronic Quad Exhaust System
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/public/Exhaust1/Exhaust1.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.Default_Material} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/Exhaust1.gltf')
