/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 V6_Engine.gltf 
Author: Davetheconqueror (https://sketchfab.com/Davetheconqueror)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/car-engine-c85c6c4fbf9e43cf8a71d2280a841d29
Title: Car Engine
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/public/V6_Engine/V6_Engine.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes['Car_2-Turbo_V6_Engine_Asembly_Designing_244,244,244_0'].geometry} material={materials['244244244']} />
          <mesh geometry={nodes['Car_2-Turbo_V6_Engine_Asembly_Designing_244,244,244_0_1'].geometry} material={materials['244244244']} />
          <mesh geometry={nodes['Car_2-Turbo_V6_Engine_Asembly_Designing_244,244,244_0_2'].geometry} material={materials['244244244']} />
          <mesh geometry={nodes['Car_2-Turbo_V6_Engine_Asembly_Designing_244,244,244_0_3'].geometry} material={materials['244244244']} />
          <mesh geometry={nodes['Car_2-Turbo_V6_Engine_Asembly_Designing_244,244,244_0_4'].geometry} material={materials['244244244']} />
          <mesh geometry={nodes['Car_2-Turbo_V6_Engine_Asembly_Designing_244,244,244_0_5'].geometry} material={materials['244244244']} />
          <mesh geometry={nodes['Car_2-Turbo_V6_Engine_Asembly_Designing_244,244,244_0_6'].geometry} material={materials['244244244']} />
          <mesh geometry={nodes['Car_2-Turbo_V6_Engine_Asembly_Designing_244,244,244_0_7'].geometry} material={materials['244244244']} />
          <mesh geometry={nodes['Car_2-Turbo_V6_Engine_Asembly_Designing_244,244,244_0_8'].geometry} material={materials['244244244']} />
          <mesh geometry={nodes['Car_2-Turbo_V6_Engine_Asembly_Designing_244,244,244_0_9'].geometry} material={materials['244244244']} />
          <mesh geometry={nodes['Car_2-Turbo_V6_Engine_Asembly_Designing_Base_0'].geometry} material={materials.Base} />
          <mesh geometry={nodes['Car_2-Turbo_V6_Engine_Asembly_Designing_255,241,177_0'].geometry} material={materials['255241177']} />
          <mesh geometry={nodes['Car_2-Turbo_V6_Engine_Asembly_Designing_255,241,177_0_1'].geometry} material={materials['255241177']} />
          <mesh geometry={nodes['Car_2-Turbo_V6_Engine_Asembly_Designing_190,188,186_1_0'].geometry} material={materials['190188186_1']} />
          <mesh geometry={nodes['Car_2-Turbo_V6_Engine_Asembly_Designing_190,188,186_0'].geometry} material={materials['190188186']} />
          <mesh geometry={nodes['Car_2-Turbo_V6_Engine_Asembly_Designing_190,188,186_0_1'].geometry} material={materials['190188186']} />
          <mesh geometry={nodes['Car_2-Turbo_V6_Engine_Asembly_Designing_255,255,255_0'].geometry} material={materials['255255255']} />
          <mesh geometry={nodes['Car_2-Turbo_V6_Engine_Asembly_Designing_72,71,61_0'].geometry} material={materials['727161']} />
          <mesh geometry={nodes['Car_2-Turbo_V6_Engine_Asembly_Designing_203,154,59_0'].geometry} material={materials['20315459']} />
          <mesh geometry={nodes['Car_2-Turbo_V6_Engine_Asembly_Designing_255,251,240_0'].geometry} material={materials['255251240']} />
          <mesh geometry={nodes['Car_2-Turbo_V6_Engine_Asembly_Designing_179,141,1_0'].geometry} material={materials['1791411']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/V6_Engine.gltf')
