/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Wheel1.gltf 
Author: Orzechu (https://sketchfab.com/Orzechu)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/offroad-wheel-4x4-9ed2b7edfbc84eb79696ed7b20e05cda
Title: Offroad wheel 4x4
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/public/Wheel1/Wheel1.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.2}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_4.geometry} material={materials['Material.002']} position={[-0.367, 0, 0]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Wheel1.gltf')
